version: '3.8'
services:
  messages_db:
    image: postgres:latest
    container_name: messages-db
    environment:
      POSTGRES_DB: messages
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - messages_data:/var/lib/postgresql/data

  identity_db:
    image: postgres:latest
    container_name: identity-db
    environment:
      POSTGRES_DB: identity
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5442:5432"
    volumes:
      - identity_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  messages-api:
    build:
      context: ..
      dockerfile: Services/Messages/MeSender.Messages.WebApi/Dockerfile
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - JWT_SECRET=your-super-secret-key-with-minimum-32-characters
      - JWT_ISSUER=MeSender
      - JWT_AUDIENCE=MeSender
    depends_on:
      - messages_db

  identity-api:
    build:
      context: ..
      dockerfile: Services/Identity/MeSender.Identity.WebApi/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - JWT_SECRET=your-super-secret-key-with-minimum-32-characters
      - JWT_REFRESH_SECRET=your-super-secret-refresh-key-with-minimum-32-characters
      - JWT_ISSUER=MeSender
      - JWT_AUDIENCE=MeSender
      - JWT_ACCESS_TOKEN_EXPIRATION=00:15:00
      - JWT_REFRESH_TOKEN_EXPIRATION=7.00:00:00
    depends_on:
      - identity_db
      - redis
    restart: always

volumes:
  messages_data:
  identity_data: