version: '3.8'
services:
  messages_db:
    image: postgres:latest
    container_name: messages-db
    environment:
      POSTGRES_DB: messages
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - messages_data:/var/lib/postgresql/data

  identity_db:
    image: postgres:latest
    container_name: identity-db
    environment:
      POSTGRES_DB: identity
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5442:5432"
    volumes:
      - identity_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  messages_data:
  identity_data: