version: '3.8'
services:
  messages_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: messages
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - messages_data:/var/lib/postgresql/data

  identity_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: identity
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5442:5432"
    volumes:
      - identity_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    restart: unless-stopped

  jaeger:
    image: jaegertracing/all-in-one:1.56
    container_name: jaeger
    ports:
      - "16686:16686"   # UI
      - "6831:6831/udp" # Jaeger agent
      - "14268:14268"   # Collector HTTP
    networks:
      - otel-net
    restart: unless-stopped

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel.config.yaml"]
    volumes:
      - ./configs/otel.config.yaml:/etc/otel.config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC (для .NET сервисов с хоста)
      - "4318:4318"   # OTLP HTTP (если нужно)
      - "8888:8888"   # Metrics
      - "8889:8889"   # Health check
      - "13133:13133" # Health check
    depends_on:
      - prometheus
      - grafana
      - jaeger
    networks:
      - otel-net
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./configs/prometheus.config.yaml:/etc/prometheus/prometheus.config.yaml
    ports:
      - "9090:9090"
    networks:
      - otel-net

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    networks:
      - otel-net

volumes:
  messages_data:
  identity_data:
  rabbitmq_data:
  grafana-storage:

networks:
  otel-net:
    driver: bridge